[workspace]
members = [
    "armstrong-numbers",
    "beer-song",
    "difference-of-squares",
    "gigasecond",
    "hello-world",
    "leap",
    "nth-prime",
    "raindrops",
    "reverse-string",
    "sum-of-multiples",
    "grains",
    "bracket-push"
]
